version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: maven build
          command: |
            mvn clean install
            mkdir -p /tmp/artifacts
            cp -r target/* /tmp/artifacts 
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
         root: ./
         paths:
           - target/        
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2.1

  buildDeploy:
    jobs:
      - build
