version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run: mvn clean install
      - persist_to_workspace:
         root: ./
         paths:
           - target/
workflows:
  version: 2

  buildDeploy:
    jobs:
      - build
