version: 2.1

workflows:
  buildDeploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: maven build
          command: |
            mvn clean install
            mkdir -p /tmp/artifacts
            cp -r target/* /tmp/artifacts 
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
         root: ./
         paths:
           - target/        
      - store_artifacts:
          path: /tmp/artifacts
      - setup_remote_docker
      - run: 
          name: Publish Docker Image to Docker Hub
          command: |
           if [[ -z "$CIRCLE_TAG" ]] ;  then exit 1; fi
            TAG=$CIRCLE_TAG
		        echo $DOCKER_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            REPONAME=$DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME
            docker build -t $REPONAME:$TAG . 

  